name: "Eliza's Photos"
favicon: null
layout_spectrum: 0.6475913834292442
typography_spectrum: 0.3258155668154359
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6274673957377672
  lightness: 0.6064866185188293
  saturation: 0.3077947231940925
  rhythmicContrast: 0.3250419106334448
purpose: []
